### ISSUE TITLE
Azure Ear: usb.core.USBTimeoutError: [Errno 110] Operation timed out on Device Authentication

### ISSUE THREAD

**Issue by XavierGeerinck** [christian-vorhemus/azure-percept-py#10]
When I install the device, I always get "Operation time out"

1. I connect the USB
2. I allow udev access by adding `SUBSYSTEM=="usb", ATTR{idVendor}=="045e", ATTR{idProduct}=="0673", MODE="666"` and reloading it
3. I run the Azure Ear example

Stack:

```python
➜ python azure-percept-test.py
Authenticating sensor...
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/home/user/.pyenv/versions/3.8.12/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/home/user/.pyenv/versions/3.8.12/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/user/.pyenv/versions/3.8.12/lib/python3.8/site-packages/azure/iot/percept/_device_authentication.py", line 94, in start_authentication
    read_msg = dev.read(self.read_endpoint, 5120)
  File "/home/user/.pyenv/versions/3.8.12/lib/python3.8/site-packages/usb/core.py", line 1029, in read
    ret = fn(
  File "/home/user/.pyenv/versions/3.8.12/lib/python3.8/site-packages/usb/backend/libusb1.py", line 846, in bulk_read
    return self.__read(self.lib.libusb_bulk_transfer,
  File "/home/user/.pyenv/versions/3.8.12/lib/python3.8/site-packages/usb/backend/libusb1.py", line 954, in __read
    _check(retval)
  File "/home/user/.pyenv/versions/3.8.12/lib/python3.8/site-packages/usb/backend/libusb1.py", line 602, in _check
    raise USBTimeoutError(_strerror(ret), ret, _libusb_errno[ret])
usb.core.USBTimeoutError: [Errno 110] Operation timed out
```

**Comment by XavierGeerinck** [comment]
Not sure if relevant, but I have: "bcdDevice              :    0x8 Device 0.08"

**Comment by XavierGeerinck** [comment]
Update: It progresses, but fails at "Authentication Failed" now:

> Note: I patched the write part to use `_send_to_usb` to resolve the operation time out

https://github.com/christian-vorhemus/azure-percept-py/blob/main/iot/percept/_device_authentication.py#L92

```
Authenticating sensor...
Msg length: 2
Write: [119, 1] 2
Read: array('B', [119, 2, 22, 3, 3, 0, 153, 1, 0, 0, 149, 3, 3, 255, 255, 255, 255, 48, 91, 54, 136, 87, 73, 68, 226, 183, 90, 172, 215, 96, 16, 29, 143, 107, 200, 33, 157, 84, 35, 158, 163, 6, 185, 124, 47, 0, 0, 14, 192, 44, 192, 48, 192, 43, 192, 47, 0, 157, 0, 156, 0, 255, 1, 0, 0, 94, 0, 0, 0, 36, 0, 34, 0, 0, 31, 97, 117, 116, 104, 46, 112, 114, 111, 106, 101, 99, 116, 115, 97, 110, 116, 97, 99, 114, 117, 122, 46, 97, 122, 117, 114, 101, 46, 110, 101, 116, 0, 13, 0, 22, 0, 20, 6, 3, 6, 1, 5, 3, 5, 1, 4, 3, 4, 1, 3, 3, 3, 1, 2, 3, 2, 1, 0, 10, 0, 10, 0, 8, 0, 24, 0, 23, 0, 22, 0, 26, 0, 11, 0, 2, 1, 0, 0, 23, 0, 0, 0, 35, 0, 0])
160
Msg length: 5
Write: [22, 3, 3, 13, 177] 5
Read: array('B', [119, 4])
2
================================================================================================
Authenticating sensor...
Msg length: 2
Write: [119, 1] 2
Read: array('B', [0, 94, 0, 0, 0, 36, 0, 34, 0, 0, 31, 97, 117, 116, 104, 46, 112, 114, 111, 106, 101, 99, 116, 115, 97, 110, 116, 97, 99, 114, 117, 122, 46, 97, 122, 117, 114, 101, 46, 110, 101, 116, 0, 13, 0, 22, 0, 20, 6, 3, 6, 1, 5, 3, 5, 1, 4, 3, 4, 1, 3, 3, 3, 1, 2, 3, 2, 1, 0, 10, 0, 10, 0, 8, 0, 24, 0, 23, 0, 22, 0, 26, 0, 11, 0, 2, 1, 0, 0, 23, 0, 0, 0, 35, 0, 0])
96
================================================================================================
Authenticating sensor...
Msg length: 2
Write: [119, 1] 2
Read: array('B', [119, 3, 5, 0, 0, 0])
6
================================================================================================
Authenticating sensor...
Msg length: 2
Write: [119, 1] 2
Read: array('B', [119, 2, 22, 3, 3, 0, 153, 1, 0, 0, 149, 3, 3, 255, 255, 255, 255, 99, 162, 212, 105, 144, 56, 173, 16, 1, 107, 221, 191, 241, 136, 254, 173, 194, 239, 183, 130, 209, 239, 72, 245, 155, 36, 29, 115, 0, 0, 14, 192, 44, 192, 48, 192, 43, 192, 47, 0, 157, 0, 156, 0, 255, 1, 0, 0, 94, 0, 0, 0, 36, 0, 34, 0, 0, 31, 97, 117, 116, 104, 46, 112, 114, 111, 106, 101, 99, 116, 115, 97, 110, 116, 97, 99, 114, 117, 122, 46, 97, 122, 117, 114, 101, 46, 110, 101, 116, 0, 13, 0, 22, 0, 20, 6, 3, 6, 1, 5, 3, 5, 1, 4, 3, 4, 1, 3, 3, 3, 1, 2, 3, 2, 1, 0, 10, 0, 10, 0, 8, 0, 24, 0, 23, 0, 22, 0, 26, 0, 11, 0, 2, 1, 0, 0, 23, 0, 0, 0, 35, 0, 0])
160
Msg length: 5
Write: [22, 3, 3, 13, 177] 5
Read: array('B', [119, 3, 3, 0, 0, 0])
6
Msg length: 3
Write: [2, 0, 0] 3
Read: array('B', [119, 4])
2
Authentication failed
```

**Comment by christian-vorhemus** [comment]
Hello @XavierGeerinck ,

concering the udev rules, there are already predefined ones in `/etc/udev/rules.d/80-azurepercept-accessories.rules` which apply to the group `apdk_accessories` - have you tried adding the user which executes the script to this group with `sudo usermod -aG apdk_accessories,audio user` ?

**Comment by XavierGeerinck** [comment]
Hi @christian-vorhemus I added the authentication read / write responses since I indeed was able to get past the operation time out part. So I guess the udev is then correctly set up?

**Comment by christian-vorhemus** [comment]
The communication to the USB device appears to be working indeed, the last write that happens

`Write: [2, 0, 0]`

seems to cause the issue because the device is responding with [119, 4] whereas 119 (or 0x77 in hex) is the message header and 4 is the payload which indicates a failed attempt to authenticate or in other words, the device expected a different message than what it got. Let me see if I can reproduce the issue on my end.

**Comment by XavierGeerinck** [comment]
Awesome! Thanks a lot, if required I am available today (whenever you have time!) so I can show you as well on a teams call

**Comment by christian-vorhemus** [comment]
@XavierGeerinck - I can confirm the bug on a newly flashed Azure Percept device. To unblock you, can you try to build and run [this](https://gist.github.com/christian-vorhemus/b023a7132f3a649f3789b1a4453921ef) program with `sudo gcc validator.c -lpthread -ludev -lusb-1.0 -o validator` and `sudo ./validator` on your Percept? It takes care of the authentication of the audio sensor. Afterwards the azure-percept Python library should be capable of recording audio. This is just a workaround until the fix is in place.

**Comment by XavierGeerinck** [comment]
That worked! Thank you so much, this unblocks me 😊

Wondering as well, is the root cause known? I am interested to learn more about what the issue was

**Comment by christian-vorhemus** [comment]
@XavierGeerinck - the problem should be fixed in version 0.0.10 which is now published. 

To give a bit more context, at one step in the process you posted above the sensor returned `Read: array('B', [119, 3, 3, 0, 0, 0])`. The first 2 bytes are header information, the next 4 bytes tell us how many bytes the SoM expects from the data we've received from the remote attestation service which is [3, 0, 0, 0] or 3 bytes. This is also why in the next step `Write: [2, 0, 0]` 3 bytes are written. However, what the sensor should have actually returned is [119, 3, 177, 13, 0, 0] which is 3505 interpreted as integer in little endian. Since the sensor didn't get the expected 3505 bytes, it returned [119, 4] which means "failed".

To be frank I don't know why the SoM reacts that way and why this suddenly appeared, however, my previous solution was error prone as it relied on timeouts to wait for web service calls to finish - while the new solution based on the validation of the azureeyemodule makes use of epolls to notify the authentication process when new data arrived at the socket.

**Comment by XavierGeerinck** [comment]
Thanks a lot @christian-vorhemus ! This helped a lot to understand what is going on. I have now tested it on the latest version and it is indeed working as intended. So I will close this :)
